        version: '3'
        services:
            postgres:
                container_name: postgres
                image: postgres
                environment:
                    POSTGRES_USER: postgres
                    POSTGRES_PASSWORD: secret
                ports:
                    - "5432:5432"
            tiled:
                container_name: tiled
                image: ghcr.io/bluesky/tiled:main
                environment:
                    TILED_SINGLE_USER_API_KEY: secret
                    TILED_TEST_POSTGRESQL_URI: postgresql+asyncpg://postgres:secret@postgres:5432
                depends_on:
                    - postgres
                ports:
                    - "8000:8000"