name: Publish Postgres Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Compose
        uses: isbang/compose-action@v1.5.1
        with:
          compose-file: "./docker-compose.yml"

      - name: Start containers
        run: docker-compose up -d

      - name: Wait for containers to start
        run: sleep 10

      - name: Create Tiled catalog
        run: docker exec -it tiled tiled catalog init postgresql+asyncpg://postgres:secret@postgres:5432

      - name: Stop containers
        run: docker-compose down

