name: Publish Database Images

on:
    push:
      branches:
        - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - uses: actions/setup-python@v4
        with:
          python-version: "3.x"
          cache: 'pip'
      - run: pip install tiled

      - name: Start PostgreSQL service in container.
        shell: bash -l {0}
        run: | 
            set -e
            docker run -d --rm --name postgres -p 5432:5432 -e POSTGRES_PASSWORD=secret -d docker.io/postgres
            docker ps

      - name: Run Tiled commands.
        shell: bash -l {0}
        run: source scripts/run_tiled.sh
        env:
          # Specify Database Connection
          TILED_TEST_POSTGRESQL_URI: postgresql+asyncpg://postgres:secret@localhost:5432


    
