name: Publish Database Images

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Compose
        uses: isbang/compose-action@v1.5.1
        with:
          compose-file: "./docker-compose.yml"

      - name: Start containers
        run: docker-compose up -d

      - name: Wait for containers to start
        run: sleep 10

      - name: Create Tiled catalog
        run: docker exec -i tiled-test-db tiled catalog init postgresql+asyncpg://postgres:secret@postgres:5432

      - name: Dump sql data into binary format
        run: docker exec -i postgres /bin/bash -c "PGPASSWORD=secret pg_dump --username postgres postgres" > tiled_test_db_pg.sql

      - name: Stop containers
        run: docker-compose down

      - name: Publish .sql files to github release with action
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            tiled_test_db_pg.sql
          tag_name: ${{ github.ref }}
          body: |
            ${{ github.ref }} : ${{ github.event.head_commit.message }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    
